---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3266744/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp madumateknik.png $DEPLOYPATH
    - /bin/cp bower.json $DEPLOYPATH
    - /bin/cp CHANGELOG.md $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp gulpfile.js $DEPLOYPATH
    - /bin/cp LICENSE.md $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp product-detail-tokico-1-2inch-dn15.html $DEPLOYPATH
    - /bin/cp product-detail-tokico-1-2inch-dn20.html $DEPLOYPATH
    - /bin/cp product-detail-tokico-1inch-dn25.html $DEPLOYPATH
    - /bin/cp product-detail-tokico-2inch-dn50.html $DEPLOYPATH
    - /bin/cp pr-amico-1per2in-dn15.html $DEPLOYPATH
    - /bin/cp pr-amico-2in-dn50.html $DEPLOYPATH
    - /bin/cp pr-amico-3in-dn80.html $DEPLOYPATH
    - /bin/cp pr-amico-3per4in-dn20.html $DEPLOYPATH
    - /bin/cp pr-shm-4inc-dn100.html $DEPLOYPATH
    - /bin/cp pr-shm-6inc-dn150.html $DEPLOYPATH
    - /bin/cp pr-shm-8inc-dn200.html $DEPLOYPATH
    - /bin/cp pr-shm-10inc-dn250.html $DEPLOYPATH
    - /bin/cp pr-shm-12inc-dn300.html $DEPLOYPATH
    - /bin/cp pr-itron-2inc-dn50.html $DEPLOYPATH
    - /bin/cp pr-itron-3inc-dn80.html $DEPLOYPATH
    - /bin/cp pr-itron-6inc-dn150.html $DEPLOYPATH
    - /bin/cp pr-itron-8inc-dn200.html $DEPLOYPATH
    - /bin/cp pr-itron-10inc-dn250.html $DEPLOYPATH
    - /bin/cp products.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH